# Generated by Django 2.1.2 on 2020-10-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20201002_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='age',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='content',
            field=models.TextField(blank=True, default='该用户很懒,什么也没写!', null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='head_img',
            field=models.CharField(blank=True, db_index=True, default='https://ss0.bdstatic.com/70cFuHSh_Q1YnxGkpoWK1HF6hhy/it/u=38616266,2952961838&fm=26&gp=0.jpg', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='nick_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
